# Generated by Django 4.2.2 on 2023-06-28 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_airline_airports_flight_passengers_travel_bookings'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='flight',
            name='time_of_departure',
            field=models.TimeField(default=datetime.time(19, 21, 3, 230857)),
        ),
    ]
