# Generated by Django 4.2.2 on 2023-06-28 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_passengers_bookings_passengers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='Passengers',
            new_name='passengers_names',
        ),
        migrations.AlterField(
            model_name='flight',
            name='time_of_departure',
            field=models.TimeField(default=datetime.time(19, 21, 54, 96508)),
        ),
    ]
