# Generated by Django 4.2.2 on 2023-06-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_travel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
